version: "3.8"

services:
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: jaques@jaques.com
      PGADMIN_DEFAULT_PASSWORD: jaques
    ports:
      - "8089:80"
    volumes:
      - "pgadmin:/root/.pgadmin"

volumes:
  pgadmin:
